services:
    petapp_nginx:
        image: nginx:alpine
        container_name: petapp_nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "8000:80"
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - petapp_app
        networks:
            - petapp_network

    petapp_app:
        build:
            context: .
            dockerfile: Dockerfile
        image: petapp_app
        container_name: petapp_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - petapp_network

networks:
    petapp_network:
        driver: bridge
